[log_schema]
    timestamp_key = "@timestamp"

[sources.apache]
    type = "file"
    include = ["/vector/config/nginx.txt"]

[sinks.console]
    type = "console"
    inputs = ["apache"]
    target = "stdout"
    encoding.codec = "json"  # Adjust the encoding according to your requirements
