[log_schema]
    timestamp_key = "@timestamp"

[sources.apache]
    type = "file"
    include = ["/tmp/git/git/apache-log.txt"]

[sinks.console]
    type = "console"
    inputs = ["apache"]
    target = "stdout"
    encoding.codec = "json"  # Adjust the encoding according to your requirements
