[log_schema]
    timestamp_key = "@timestamp"

[sources.apache]
    type = "file"
    include = ["/git/repo/vector/apache/apache-log.txt"]

[sinks.console]
    type = "console"
    inputs = ["apache"]
    target = "stdout"
    buffer.type = "memory"
    buffer.max_events = 5000
    buffer.when_full = "block"
    healthcheck.enabled = true
    encoding.codec = "json"  # Adjust the encoding according to your requirements
