[log_schema]
    timestamp_key = "@timestamp"

[sources.apache]
    type = "file"
    include = ["/git/repo/vector/apache/apache-log.txt"]

[sinks.console]
    type = "$type"
    inputs = ["apache"]
    target = "stdout"
    encoding.codec = "json"  # Adjust the encoding according to your requirements
