[log_schema]
    timestamp_key = "@timestamp"

[sources.apache]
    type = "file"
    include = ["/git/repo/vector/apache/*.txt"]
    #include = ["/git/repo/vector/apache/server-read.txt"]



[sinks.console]
    type = "console"
    inputs = ["apache"]
    target = "stdout"
    encoding.codec = "json"  # Adjust the encoding according to your requirements
